export const ADD_INGREDIENT_TO_CONSTRUCTOR: 'ADD_INGREDIENT_TO_CONSTRUCTOR' =
	'ADD_INGREDIENT_TO_CONSTRUCTOR' as const;
export const ADD_BUN_TO_CONSTRUCTOR: 'ADD_BUN_TO_CONSTRUCTOR' =
	'ADD_BUN_TO_CONSTRUCTOR' as const;
export const DELETE_INGREDIENT_FROM_CONSTRUCTOR: 'DELETE_INGREDIENT_FROM_CONSTRUCTOR' =
	'DELETE_INGREDIENT_FROM_CONSTRUCTOR' as const;
export const INCREASE_ITEM: 'INCREASE_ITEM' = 'INCREASE_ITEM' as const;
export const DECREASE_ITEM: 'DECREASE_ITEM' = 'DECREASE_ITEM' as const;
export const UPDATE_PRICE: 'UPDATE_PRICE' = 'UPDATE_PRICE' as const;
export const SWAP_ITEMS: 'SWAP_ITEMS' = 'SWAP_ITEMS' as const;
