export const OPEN_INGREDIENTS_MODAL: 'OPEN_INGREDIENTS_MODAL' =
	'OPEN_INGREDIENTS_MODAL' as const;
export const CLOSE_INGREDIENTS_MODAL: 'CLOSE_INGREDIENTS_MODAL' =
	'CLOSE_INGREDIENTS_MODAL' as const;
